packages:
  - .

overrides:
  "brace-expansion@^1.0.0": 1.1.18
  "brace-expansion@^2.0.0": 2.1.4
  "brace-expansion@>=3": 5.0.9
  "fast-uri@^3.0.0": 3.1.5
  "js-yaml@^4.0.0": 4.3.1

patchedDependencies:
  "@platformatic/kafka@2.8.0": patches/@platformatic__kafka@2.8.0.patch

allowBuilds:
  esbuild: true
